apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: churn-stack
spec:
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
