apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi
  namespace: churn-stack
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: fastapi
  endpoints:
  - port: web
    path: /metrics
    interval: 15s
  